### PR TITLE
changed echo

### PR DESCRIPTION
**Pull request by runzelu**

### CODE REVIEW

**Comment by afeld** [comment]
Does this work as expected?

**Comment by runzelu** [comment]
Yeah, I have tested it, it works just as expected. Not really?

**Comment by afeld** [comment]
Interesting. Well, I'd recommend using normal `for` loops for arrays and `arguments`, since `for...in` may include properties that you don't expect.

**Comment by runzelu** [comment]
Got it! Thank you. It's a very useful tip.

**Pull request closed without merging**
